### ISSUE TITLE
header name value support

### ISSUE THREAD

**Issue by emirhanemmez** [SMILEY4/ktor-openapi-tools#10]
First of all, it is a great library thanks for your effort. But when I check the READ.me I didn't find any documentation for header parameter. There is a headerParameter in request block but I can not add any sample value to it. Can you also add sample to READ.me for headerParameter usage?

**Comment by SMILEY4** [comment]
Thank you!  There should be some information about headers on the wiki pages for [requests](https://github.com/SMILEY4/ktor-swagger-ui/wiki/Documenting-Routes-(Request-Parameters)) and [responses](https://github.com/SMILEY4/ktor-swagger-ui/wiki/Documenting-Routes-(Responses)). Just let me know if there is anything missing.

**Comment by emirhanemmez** [comment]
Oh, I did not check wiki. Thx for info. I'm closing issue, have a good day :)
