### ISSUE TITLE
Support 3.1.0 OpenAPI specification

### ISSUE THREAD

**Issue by JaimeToca** [SMILEY4/ktor-openapi-tools#101]
https://swagger.io/specification/

**Comment by SMILEY4** [comment]
https://github.com/SMILEY4/ktor-swagger-ui/releases/tag/3.0.0-beta3

**Comment by JaimeToca** [comment]
Thank you @SMILEY4 

It seems it is not ready yet?

 https://repo.maven.apache.org/maven2/io/github/smiley4/ktor-swagger-ui/

**Comment by SMILEY4** [comment]
hi.  it usually takes a bit for maven central to publicly list it after release. it should be available in a few hours.  

Edit:  nvm, i screwed up the release :D    its fixed now and should still be available in the next few hours.
Thanks for notifying me

**Comment by JaimeToca** [comment]
Awesome @SMILEY4 !! big thanks
