### ISSUE TITLE
Incorrect display of UUIDs in Swagger between versions 2.10.0 and 3.0.0

### ISSUE THREAD

**Issue by Ziedelth** [SMILEY4/ktor-openapi-tools#102]
Hi there,

I noticed a problem with the UUID display in Swagger between versions 2.10.0 and 3.0.0. Before, the display indicated that it was a UUID string, but now it indicates that it is an object.

Is this normal behavior?

Thanks for your help.

Version 2.10.0
![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/45169338/93e69e6b-7e5e-4a09-ac3d-bda7c554d75e)

Version 3.0.0
![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/45169338/6a6a871a-3dc6-4483-a954-a3c6d4746a90)

**Comment by SMILEY4** [comment]
Hi,
i switched to my own library for generating schemas for objects. It seems like the previous generator automatically encoded UUIDs as strings which is not a default behavior with the new one.
You can configure this manually by customizing the schema generator and overwriting or redirecting UUIDs to strings
- providing a custom type processor for the UUID-type (see [here](https://github.com/SMILEY4/schema-kenerator/wiki/Custom-Type-Processing) for more info)
- "redirecting" UUID to a string (see [here](https://github.com/SMILEY4/schema-kenerator/wiki/Type-Redirects) for more info)

I tested it by simply "redirecting" and it produced the desired result:
```kotlin
install(SwaggerUI) {
    schemas {
        generator = { type ->
            type
                .collectSubTypes()
                .processReflection {
                    redirect<UUID, String>() // redirect UUID to string, i.e treat is as a string for schema generation
                }
                .connectSubTypes()
                .handleNameAnnotation()
                .generateSwaggerSchema()
                .handleCoreAnnotations()
                .withAutoTitle(TitleType.SIMPLE)
                .compileReferencingRoot()
        }
    }
}
```
