### ISSUE TITLE
KtorDsl annotation for dsl methods

### ISSUE THREAD

**Issue by chameleon82** [SMILEY4/ktor-openapi-tools#11]
Ktor framework dsl methods marked with `@KtorDsl` annotation. Is there any profit to add that annotation to ktor-swagger-ui dsl methods?

I don't know actual benefits of having that, but only noticed Idea highlight dsl marked methods. Asking for comments.

**Comment by SMILEY4** [comment]
`@KtorDsl` (i.e. `@DslMarker`) marks an element as part of a dsl and limits its use in nested blocks, so dsl-elements can't be used where they shouldn't be used. 

Short Example:
```kotlin
@DslMarker
annotation class MyDslMarker // same as "KtorDsl"

@MyDslMarker
class MyElementA

@MyDslMarker
class MyElementB

fun buildA(block: MyElementA.() -> Unit) = MyElementA().apply(block)

fun MyElementA.buildB(block: MyElementB.() -> Unit) = MyElementB().apply(block)

fun main() {
    buildA { 
        buildB {
            buildB {} // not possible and marked as an error, because MyElementA and MyElementB are both annotated with MyDslMarker
        }
    }
}
```

More information about this annotation and its usage in the kotlin documentation: https://kotlinlang.org/docs/type-safe-builders.html#scope-control-dslmarker.

It seems like i forgot to add it to most of the ktor functions though :)
