### ISSUE TITLE
Rate limiting scope included

### ISSUE THREAD

**Issue by max-f** [SMILEY4/ktor-openapi-tools#110]
Hi, 
a rate limited endpoint like 
```kotlin
routing {
        rateLimit(RateLimitName("limit")) {
            rateLimitedRoutes()
        }
}

fun Route.rateLimitedRoutes() {
    route("/rated") {
        get("hello", {
            description = "Returns a rated greeting"
            tags = setOf("Public")
        }) {
            call.respondText("ratedHello")
        }
    }
}
```
seems to result in a wrong path in the generated openapi spec / swagger-ui:
![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/501518/a1f59f78-e817-4859-a52f-528d81801e74)

Is there a way to 'overwrite' or otherwise circumvent that behavior?

**Comment by SMILEY4** [comment]
Hi,
you can ignore parts of the route in the [plugin config](https://github.com/SMILEY4/ktor-swagger-ui/wiki/Plugin-and-Swagger-Configuration) using `ignoredRouteSelectors`. You can add the rate limiter routeSelector to this list and it will not be included in the spec.
