### ISSUE TITLE
No code completion when using `to` inside OpenApiResponses

### ISSUE THREAD

**Issue by Him188** [SMILEY4/ktor-openapi-tools#112]
When you add a reponse code definition like this:

```kotlin
post({
    description = "test"
    response {
        HttpStatusCode.Created to {
            description = "Subject created"
            body<CreateApiKeyResponse>()
        }
    }
}) 
```

You always have to type `HttpStatusCode.` before IDE can help you.

Also the  `to` with a lambda sounds odd to me, as the standard library use it to create a `Pair`. It really sounds like the `to` will create a Pair and does not register something.

What I would suggest is:

```kotlin
post({
    description = "test"
    response {
        code(HttpStatusCode.Created) {
            description = "Subject created"
            body<CreateApiKeyResponse>()
        }
        code(HttpStatusCode.Conflict) {
            description = "You have reached the limit"
            body<Unit>()
        }
    }
}) {

}
```

You type smaller case `code` without pressing shift, you press enter, then IDE will prompt for completion for HttpStatusCode. This could give both better typing experience and looking.

![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/12100985/8f0ba541-44bb-4a2b-91b1-5911845db9ff)

**Comment by SMILEY4** [comment]
hi, thanks for your suggestions. I added some improvements / alternatives to the dsl which are included in version 3.2.0.
