### ISSUE TITLE
Add vararg shotcut for adding tags

### ISSUE THREAD

**Issue by Him188** [SMILEY4/ktor-openapi-tools#113]
Currently, adding tags requires writting `listOf`.
```kotlin
get({
    tags = listOf("API Key")
    summary = "Get API Key list"
})
```

I think this is better:
```kotlin
get({
    tags("API Key")
    summary = "Get API Key list"
})
```

**Comment by SMILEY4** [comment]
hi, thanks for your suggestions. I added some improvements / alternatives to the dsl which are included in version 3.2.0.
