### ISSUE TITLE
 v3.x missing feature - configuring the schema encoder

### ISSUE THREAD

**Issue by Sterta** [SMILEY4/ktor-openapi-tools#117]
Before 3.x it was possible for example to do something like this:

```kotlin
typealias SchemaEncoder = (type: SchemaType) -> String?
````

```kotlin
    encoding {
        schemaEncoder { type ->
            when (type.javaType) {
                ByteArrayWrapper::class.java -> jssJson.encodeToSchema(
                    serializer = ByteArrayWrapperSerializer
                )

                UUID::class.java -> jssJson.encodeToSchema(
                  serializer = UUIDSerializer
                )
                OffsetDateTime::class.java -> jssJson.encodeToSchema(
                    serializer = OffsetDateTimeSerializer
                )

                else -> {
                    jssJson.encodeToSchema(
                        serializer = serializer(type)
                    )
                }
            }
        }
        schemaDefinitionsField = "definitions"
    }
```
For the example encoder it is possible with 3.x.

I couldn't find a way to implement the schema encoder example with 3.x.

Is this not possible anymore, or is their a way?

If not, is it possible to add this functionality again?

**Comment by SMILEY4** [comment]
The "old" schema generator was replaced with a completely new one which works a quite bit different now. You can customize this new schema generator, some information [here](https://github.com/SMILEY4/ktor-swagger-ui/wiki/Customizing-Schema-Generation).

You can then for example:
- customize the general schema generation steps, to e.g. handle swagger or jackson annotations (more info [here](https://github.com/SMILEY4/schema-kenerator/wiki/Modules-Overview))
- generate a specific type as another given type via [type redirects](https://github.com/SMILEY4/schema-kenerator/wiki/Type-Redirects)
- completly customize the input data for the schema generation via [custom type processors](https://github.com/SMILEY4/schema-kenerator/wiki/Custom-Type-Processing)

there is currently also an open [issue](https://github.com/SMILEY4/ktor-swagger-ui/issues/115) about custom schema for LocalDateTime that might be relevant.

I hope these links are helpful enough. I'm still working on the new schema generator and the wiki, so if you encounter any questions or issues, please let me know.
