### ISSUE TITLE
Automatically set `required=true` for path parameters

### ISSUE THREAD

**Issue by mnonnenmacher** [SMILEY4/ktor-openapi-tools#118]
Currently, the `required` property must be set manually for path parameters:

```kotlin
request {
    pathParameter<Long>("param") {
        required = true
    }
}
```

It would be great if the property could be set to `true` automatically for path parameters, because the [specification](https://spec.openapis.org/oas/v3.1.0#parameter-locations) for the `required` property states that:

> If the [parameter location](https://spec.openapis.org/oas/v3.1.0#parameterIn) is "path", this property is REQUIRED and its value MUST be true.

**Comment by SMILEY4** [comment]
thanks for the suggestion.
Default for path-parameters is now required=true. The change will be included in the next version soon.
