### ISSUE TITLE
Referenced schema dropped from output

### ISSUE THREAD

**Issue by BlackHornet** [SMILEY4/ktor-openapi-tools#12]
Hello,
I'm facing the problem, that my referenced Schema is dropped from the generated swagger-ui components (missing in api.json file as well).

After providing some openapi schemas, they are only added to the final swagger components when they referenced a request or response as a body.

* define openapi Schema.A and Schema.B
* Schema.A has a property referencing Schema.B
* Having a ktor route with Schema.A as response body only.
* install SwaggerUI feature with `schemasInComponentSection = true`

In the resulting Swagger-UI Schema.B is missing as a component and in the response body description of previously defined route.

Is that an issue, or what can I do?

**Comment by SMILEY4** [comment]
Hi,
i'm not quite sure i understand the problem you are facing correctly. Could you maybe provide some code showing the issue, i.e. how you are defining your body/schemas ?
