### ISSUE TITLE
The schema generated for the value class is incorrect

### ISSUE THREAD

**Issue by CyanTachyon** [SMILEY4/ktor-openapi-tools#123]
I am using kotlinx for serialization, but the schema generated for the value class is incorrect. For example, I have a value class like this:

```kotlin
@JvmInline
@Serializable
value class UserId(val value: Int)
```

Then I use `UserId` in another class:

```kotlin
@Serializable
private data class LoginInfo(val email: String? = null, val id: UserId? = null, val password: String)
```

After I use `LoginInfo` as the request body, the example in the documentation becomes:

```json
{
  "email": "email",
  "password": "password",
  "id-qOkUOMs": {
    "value": 0
  }
}
```

The generated schema is:
![Screenshot 2024-08-04 200635](https://github.com/user-attachments/assets/bc07593a-d327-4633-913d-87754d610214)
However, the actual result (produced by KotlinX serialization, which is what I expect to see) is:

```json
{
  "email": "email",
  "password": "password",
  "id": 0
}
```

The documentation generated for the value class has been incorrect from version 2.X.X to the latest version 3.2.0.

I have tried several methods but none of them solved the problem, unless I do not use the value class.

**Comment by SMILEY4** [comment]
Hi,  thanks for reporting the issue.

I managed to fix it and value classes should now be correctly inlined with their respective ("wrapped") type. The changes will be included in the next version.

**Comment by CyanTachyon** [comment]
> Hi, thanks for reporting the issue.
> 
> I managed to fix it and value classes should now be correctly inlined with their respective ("wrapped") type. The changes will be included in the next version.

I see that the schema generation error has been fixed, and the current schema is correct. However, the example remains the same as before, just as I mentioned above.
