### ISSUE TITLE
Global Type Replacement 

### ISSUE THREAD

**Issue by DebitCardz** [SMILEY4/ktor-openapi-tools#124]
Hey!
I was wondering if it was possible to globally replace `Instant` to a `int64` when it's converted to the OpenAPI Spec, when we send data from our service to whatever is consuming it we usually send Instants as Milliseconds instead of a string, so it'd be useful to just have it globally convert to a `int64`.

I read #44 but I don't think it's quite what I need.

Here is my current configuration
```kt
fun Application.configureSwaggerUi() {
    install(SwaggerUI) {
        swagger {
            displayOperationId = true
        }

        info {
            title = "API"
            version = "latest"
            description = "The auto-generated API documentation for the API"
        }

        security {
            securityScheme("account") {
                description = "Typically used for Account Authentication on the Dashboard"
                type = AuthType.HTTP
                scheme = AuthScheme.BEARER
                bearerFormat = "JWT"
            }

            securityScheme("token") {
                description = "Used for having Applications interact with the Ingot API"
                type = AuthType.HTTP
                scheme = AuthScheme.BEARER
                bearerFormat = "API Token"
            }
        }

        server {
            url = "http://localhost:8080"
            description = "Development Server"
        }

        // kotlinx support
        schemas {
            generator = { type ->
                type
                    .processKotlinxSerialization()
                    .generateSwaggerSchema()
                    .withAutoTitle(TitleType.FULL)
                    .compileInlining()
            }
        }

        ignoredRouteSelectors = ignoredRouteSelectors + RateLimitRouteSelector::class
    }
}
```
Thank you!

**Comment by SMILEY4** [comment]
Hi,

you can "redirect" the type "Instant" to e.g. "Long" in the schema generator config
```kotlin
type
    .processKotlinxSerialization {
        redirect<Instant, Long>()
    }
    .generateSwaggerSchema()
    .withAutoTitle(TitleType.FULL)
    .compileInlining()
```
this way, any occurence of an "Instance" is replaced with "Long".
You can find some more information [here](https://github.com/SMILEY4/schema-kenerator/wiki/Type-Redirects) or [here](https://github.com/SMILEY4/schema-kenerator/wiki/Custom-Type-Processing).

**Comment by DebitCardz** [comment]
Thanks for the response, it looks like using `redirect` didn't work nor did making a `customProcessor`, the output is still turning my Instant into a string on the spec.
As taken from the docs this is what I wrote
```kt
generator = { type ->
    type
        .processKotlinxSerialization {
            customProcessor<Instant> {
                PrimitiveTypeData(
                    id = TypeId.build(Long::class.qualifiedName!!),
                    simpleName = Long::class.simpleName!!,
                    qualifiedName = Long::class.qualifiedName!!,
                )
            }
            redirect<Instant, Long>()
        }
        .generateSwaggerSchema()
        .withAutoTitle(TitleType.FULL)
        .compileInlining()
}
``` 
Of course I didn't put customProcessor and the redirect together but I tried them both individually.

**Comment by DebitCardz** [comment]
Hey! After some more experimentation I found the issue.
My model definition was like this,
```kt
@Serializable
data class Example(
  val id: String,
  val created: @Contextual Instant
)
```
Using `@Contextual` makes it so the Instant doesn't get converted to a int64 during generation however, if I directly specify `@Serializable(with = /* SERIALIZER */)` that turns it into a Long it'll be generated out as a int64.

Is there any way to support `@Contextual` as it's more convenient for my team to use it.

**Comment by DebitCardz** [comment]
Very sorry for all the replies to the issue without a response back but this is related enough to this topic that I didn't want to make an entirely separate issue for this.

For our permissions we store them as an enum, like this for example.
```kt
enum class Permission(val id: String) {
  USER_WRITE("user.write"),
  ;
}
```
Then in our response back to the client we send the `id` back.
However, when I generate the schema it results in a `string`. Is it possible to make all instances of the enum `Permission` in the OpenAPI Spec use the `id` field I provide in the enum? Even if I need to do some custom processing to achieve such.

Thank you!

**Comment by SMILEY4** [comment]
> Is there any way to support `@Contextual` as it's more convenient for my team to use it.

I'm not that familiar with `@Contextual`, but i'll look into it. :)

> Is it possible to make all instances of the enum Permission in the OpenAPI Spec use the id field I provide in the enum?

Kotlinx is provinding the possible values for enums, so - as far is i know - i cant decide *later* which field/name to use. However, you could add `@SerialName("user.write")` to the enum values, though this is a kotlinx-serializer function and not a schema-kenerator one, so i'm not sure if this conflicts with something else for you. 


Just our of curiosity. Is there a specific reason you are using kotlinx over reflection for schema generation? I'm just trying to better understand how this project is used :)

**Comment by DebitCardz** [comment]
Haha thank you for your replies & apologies for sending so many questions your way.

> I'm not that familiar with `@Contextual`, but i'll look into it. :)

In kotlinx.serialization you're allowed to provide a `SerializersModule` to your JSON configuration, so it'd look something like this.
```kt
val JSON = Json {
  /* json settings. */
  
  serializersModule = SerializersModule {
    contextual(UUID::class, UUIDSerializer)
  }
}
```
Now whenever a data class like such is used against the `JSON` instance it'll automatically fetch the UUID serializer from the contextual serializer you provided.
```kt
@Serializable
data class User(val id: @Contextual UUID)

JSON.encodetoString(User(UUID.randomUUID())) // automatically converts UUID using Contextual Serializer.
```

The way to fetch the `KSerializer` is in your plugin to allow the user to specify their `SerializersModule` then retrieve it from there.
Here is a basic example of how that works,
```kt
fun kSerializerFromClass(serializersModule: SerializersModule, clazz: Class<*>): KSerializer<Any>? {
  return serializersModule.serializerOrNull(clazz)
}
```
This'll just fetch the `KSerializer` from the `SerializersModule` they specify so if one is not specified in the `Serializer` annotation it can try to fetch it from the `SerializersModule`.
> Kotlinx is provinding the possible values for enums, so - as far is i know - i cant decide later which field/name to use. However, you could add @SerialName("user.write") to the enum values, though this is a kotlinx-serializer function and not a schema-kenerator one, so i'm not sure if this conflicts with something else for you.

I think this should actually be fine, I'll test & generate the spec in a minute to see, I would've never thought of that thank you!

> Just our of curiosity. Is there a specific reason you are using kotlinx over reflection for schema generation? I'm just trying to better understand how this project is used :)

The main reason is to use custom serializers for our spec for example,
```kt
@Serializable
data class Event(
  val id: String,
  val at: @Serializable(with = InstantSerializer::class) Instant
)
```
`InstantSerializer` converts the `Instant` into its millisecond representation which is then conveyed in the generate spec because whenever we send this `Event` to the client of our API it always expects it in milliseconds.
I found kotlinx.serialization to just be more reliable than reflection for our use-case and I've spent a lot of time roaming around the code understanding the basics of how everything works and trying different configurations for our auto-gen and kotlinx seemed to just work the best.

Thank you for the support, besides the `@Contextual` support & weird enum thing my team is doing the project has been very great to use, it's really boosting our teams productivity 👍

**Comment by DebitCardz** [comment]
Update, unfortunately adding `@SerialName` to the enum doesn't effect the output enum entries 😔

**Comment by SMILEY4** [comment]
thats weird. This setup ...
```kotlin
@Serializable
enum class Permission(val id: String) {
    @SerialName("user.write") USER_WRITE("user.write"),
    @SerialName("user.read") USER_READ("user.read");
}

typeOf<Permission>()
    .processKotlinxSerialization()
    .generateSwaggerSchema()
    .compileInlining()
```
... worked for me and produced the swagger schema:

```json
{
  "exampleSetFlag" : false,
  "enum" : [ "user.write", "user.read" ]
}
```

**Comment by DebitCardz** [comment]
That's so weird..
My configuration is exactly the same as I've first posted.

Let me try to make a entirely new project and see what happens with that, I also ensured everything on my project was up to date.

**Comment by DebitCardz** [comment]
!!! I lied!
I didn't add `@Serializable` to the top of my enum class, it works perfectly, I'm glad I checked back on this GH Issue because I just noticed that.

Thank you :)
