### ISSUE TITLE
missing type: string for enum types

### ISSUE THREAD

**Issue by tobyworks** [SMILEY4/ktor-openapi-tools#125]
the openapi spec is missing type: string for enum types. this causes generators like orval to generate faulty code.

<img width="460" alt="image" src="https://github.com/user-attachments/assets/e4f00caf-f061-42d7-b9c4-492ceeaa7c08">

**Comment by SMILEY4** [comment]
Hi, i'm not 100% sure i am understanding the issue correctly. Could you perhaps provide a model and openapi spec showcasing the problematic/desired behavior ?

**Comment by rmcmk** [comment]
> Hi, i'm not 100% sure i am understanding the issue correctly. Could you perhaps provide a model and openapi spec showcasing the problematic/desired behavior ?

Should be fixed by #137 once those kinks are ironed out. Same issue. Type is being stripped resulting in code generators/the UI showing the type as "unknown" or "any".

See: https://swagger.io/docs/specification/v3_0/data-models/enums/
