### ISSUE TITLE
Question. Auto generation of examples.

### ISSUE THREAD

**Issue by perracodex** [SMILEY4/ktor-openapi-tools#129]
Is there any setting to auto generate the examples instead of having to define each manually?
So that for example, when specifying in a response let's say ```body<List<Pet>>```, it can generate automatically the example for ```Pet```
Thanks

**Comment by SMILEY4** [comment]
Hi, 
no, this is not supported. I don't think this would be a "simple" feature and is probably not in the scope of this plugin.
