### ISSUE TITLE
Using generics add whole canonical name in components

### ISSUE THREAD

**Issue by BlackHornet** [SMILEY4/ktor-openapi-tools#13]
At the moment i am working on a small REST project.

When I try to prepare some routes to retrieve list and single items from a database table
GET /item
GET /item/XYZ

I want the first one to return a List of "Item", while the second one to return just "Item"

When I am using `body<List<Item>>` it automatically creates a component with full canonical name: Result in api.json
```
"responses" : {
  "200" : {
    "description" : "successful operation",
    "headers" : { },
    "content" : {
      "application/json" : {
        "schema" : {
          "type" : "array",
          "xml" : { },
          "items" : {
            "$ref" : "#/components/schemas/com.example.ktor.Item"
          }
        }
      }
    }
  }
}
```

When I try to create the body manually providing a custom schema for my Item:
```
body {
  mediaType(ContentType.Application.Json)
    ArraySchema().apply {
      items = ObjectSchema().apply {
      `$ref` = "Item"
    }
  }
}
```
The created api.json response is just empty
```
"responses" : {
  "200" : {
    "description" : "successful operation",
    "headers" : { },
    "content" : {
      "application/json" : { }
    }
  }
}
```

Do you have any idea how to get it working?

**Comment by SMILEY4** [comment]
Hi,

There are basically three ways to provide a schema:

via generics:
```kotlin
body<MyType> { // auto-generates schema from "MyType"
  mediaType(ContentType.Application.Json)
}
```

as a parameter:
```kotlin
body(MyType::class) { // auto-generates schema from "MyType"
  mediaType(ContentType.Application.Json)
}
```

as a custom schema (e.g. as a openapi-schema-object like you have in your second example):
```kotlin
install(SwaggerUI) {
    schemas {
      openApi("myType") { // custom schema with id "myType"
        ArraySchema().apply {
          items = ObjectSchema().apply {
            `$ref` = "Item"
          }
        }
      }
   }
}

body("myType") { // reference custom schema by id "myType"
  mediaType(ContentType.Application.Json)
}
```
So in your second example, you are using `body {` without providing any type, since the `ArraySchema().apply {...` has no effect where it is placed, resulting in an empty body with no schema


More information about how to define bodies can be found in the wiki: https://github.com/SMILEY4/ktor-swagger-ui/wiki/Documenting-Routes-(Bodies)

I hope i could clear things up, if there are any open questions left, feel free to ask.

**Comment by clragon** [comment]
I dont quite understand this just yet.
When I make my own wrapper type, it leads to the above mentioned full canonical name.

![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/11785085/20df524c-f9b4-4439-b4a6-940c40ca8f65)

Specified as `body<Page<ProjectVersion>>`.

The schema is correct, it just has an unwieldy name.

Is there no possibility for me to just _not_ have the fully qualified name, without having to create an ID for the schema?
I have a lot of these and I don't really wanna make IDs for them.
