### ISSUE TITLE
OpenApiResponses.code incorrectly uses toString on statusCode

### ISSUE THREAD

**Issue by NecroKote** [SMILEY4/ktor-openapi-tools#131]
On the following line:

https://github.com/SMILEY4/ktor-swagger-ui/blob/013161a5c301a331e707e393fecfc13c4e405ec4/ktor-swagger-ui/src/main/kotlin/io/github/smiley4/ktorswaggerui/dsl/routes/OpenApiResponses.kt#L38

`statusCode.toString()` should be replaced with `statusCode.value.toString()` 

Otherwise, the resulting schema contains incorrect values. For example, with `code(HttpStatusCode.BadRequest)`:
```json
"responses": {
    "400 Bad Request": {
        "headers": {...},
        "content": {...}
    }
}
```

For the time being, I'm using following workaround:
```kotlin
fun OpenApiResponses.status(code: HttpStatusCode, block: OpenApiResponse.() -> Unit) {
    return code(code.value.toString(), block)
}
```

**Comment by SMILEY4** [comment]
Hi,  thanks for the info :+1: 
the bug is fixed and included in  version 3.5.0
