### ISSUE TITLE
Cookie Parameter Location Support

### ISSUE THREAD

**Issue by mantasjasikenas** [SMILEY4/ktor-openapi-tools#142]
Currently, the plugin covers `QUERY`, `HEADER`, and `PATH` parameter locations for requests but lacks support for `COOKIE` parameter location. Implementing this would improve flexibility.

Thanks in advance!

**Comment by SMILEY4** [comment]
Hi,  thanks for the suggestion.
Support for cookie parameters will be included in the next version.
