### ISSUE TITLE
🐛 Bug in the RouteCollector squashes nested routes with trailing slashes in the parent

### ISSUE THREAD

**Issue by jens-brimfors-wolt** [SMILEY4/ktor-openapi-tools#145]
# Problem
```
route("/nested/"){
  get("/foo"){
    call.respond("Helloo")
  }
}
```
should become `/nested/foo`, but is instead squashed into `//foo`

# Demo
https://github.com/SMILEY4/ktor-swagger-ui/compare/develop...jens-brimfors-wolt:ktor-swagger-ui:unable_to_handle_trailing_slash_as_part_of_a_multi-part_DSL_route
I made a test of the wholey untested RouteCollector to prove the bug

# PS
I gave it a try fixing it, but cant give it more right now, so I hope this bug-report will find you well, and put you on the right track of fixing the issue

**Comment by SMILEY4** [comment]
Hi,  thanks for reporting the issue.
I found the bug and the fix will be included in the next version soon.
I somehow didn't think a "trailing" slash could be placed in the middle of a route, leading to everything before that getting dropped ... oops :)

**Comment by jens-brimfors-wolt** [comment]
Thank you very much 🙇
