### ISSUE TITLE
WebJars plugin breaks GraalVM Native Image building

### ISSUE THREAD

**Issue by Skater901** [SMILEY4/ktor-openapi-tools#146]
I tried using GraalVM to build a Native Image of my project using `ktor-swagger-ui`, but the build failed with the following errors:

```
Error: Unsupported features in 5 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime. If these objects should not be stored in the image heap, you can use

    '--trace-object-instantiation=java.util.jar.JarFile'

to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with

    '--initialize-at-run-time=<culprit>'

to prevent the instantiation of the object.
The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
```

I spent some time debugging, and was able to figure out that the problem is the presence of the Ktor WebJars plugin. Specifically, [this](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/ktor-swagger-ui/src/main/kotlin/io/github/smiley4/ktorswaggerui/SwaggerPlugin.kt#L62-L63).

I made my own artifact locally of `ktor-swagger-ui` without the WebJars plugin, and my native image built successfully. Additionally, I tested my application, and the Swagger UI was still available, even with WebJars removed.

Since the WebJars plugin doesn't seem to actually be needed for `ktor-swagger-ui` to work, is it possible to remove it? Or, if it is needed and I've just missed how it's needed, is it possible to make it a configurable option, so that I can disable the WebJars plugin? (And potentially exclude it from my dependencies, if required)

**Comment by SMILEY4** [comment]
Hi,
i haven't tested in quite some time without the webjars plugin so i'm not sure why i originally added it, but with your and my testing, it seems like its not required.
I'll remove it  with the next version :+1:
