### ISSUE TITLE
SPA route included in OpenAPI documentation

### ISSUE THREAD

**Issue by blinchk** [SMILEY4/ktor-openapi-tools#15]
**What is wrong?**
Using singlePageApplication route to serve Vue application, but looks wrong that route is present in OpenAPI documentation.

**Version:** 1.0.1

**Source code**
```kotlin
fun Application.configureRouting() {
    routing {
        singlePageApplication {
            vue("ktor-playground-vue/dist")
        }

        route("api") {
            articleRoutes()
        }
    }
}
```
**Actual result**

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/49353043/212554646-8ea35a4b-7df9-44c6-b261-10d04bef0082.png">

```log 
2023-01-15 19:01:32.921 DEBUG --- [           main] i.g.s.k.specbuilder.OApiPathsBuilder    : Configure path: GET //{...}
```

**Temporary fix**
```kotlin
fun Application.configureSwagger() {
    install(SwaggerUI) {
        pathFilter = { _, url -> url.firstOrNull() == "api" }
    }
}
```

**Comment by SMILEY4** [comment]
Hi,  I have only quickly looked into this, but from what i understand, i can't really safely distinguish between "normal" routes and routes for an spa to only hide those. Only difference (that i found) is the name "static-content-path-parameter" for one of the route-parts.
Maybe one option would be to make it possible to hide all routes for static resources (i.e. the ones that contain that name) via a flag in the plugin-config ?  Don't know how useful this would be (especially compared to the existing `pathFilter`) ?

**Comment by blinchk** [comment]
Generally, this is unnecessary to exclude SPA routes, because in common case REST routes are separated to different path and `pathFilter` is great solution for it.

Anyway, thanks for discussion about it.
