### ISSUE TITLE
How to add field description

### ISSUE THREAD

**Issue by Eternal-CP** [SMILEY4/ktor-openapi-tools#154]
How to add field description to Schema

**Comment by s-frei** [comment]
Maybe use annotations as described here https://github.com/SMILEY4/schema-kenerator/blob/b5c2d56ded43beaf47e4720af6758c3aaefc9201/schema-kenerator-examples/src/test/kotlin/io/github/smiley4/schemakenerator/examples/E03_Generating_Swagger_Schema.kt#L473
