### ISSUE TITLE
Example for common schema generation like Instant, LocalDate

### ISSUE THREAD

**Issue by anderssonw** [SMILEY4/ktor-openapi-tools#155]
The example which is currently present only shows how to handle it for a top-level LocalDateTime. I currently have the following setup:

```kotlin
generator = { type ->
    type
        .processReflection {
            redirect<Instant, String>()
            redirect<LocalDate, String>()
        }
        .connectSubTypes()
        .generateSwaggerSchema {}
        .withTitle(TitleType.SIMPLE)
        .compileReferencingRoot()
}
```

Which is _fine_, but I would love to be able to specify the schema type such that this (`registreringstidspunkt` is an Instant):

<img width="268" alt="image" src="https://github.com/user-attachments/assets/eafe572a-0897-484c-a029-6ac2c4abd268">

becomes this:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/7897a00b-be60-44a2-bc08-dc3cf2b6c9bc">

Which was something I was able to do using an older library, Kompendium, but I'm not entirely sure how to setup using ktor-swagger-ui and schema-kenerator

**Comment by s-frei** [comment]
Have a look at: https://github.com/SMILEY4/ktor-swagger-ui/issues/135

**Comment by anderssonw** [comment]
I've gave it a little shot now, but I have an issue. Just dumping the current setup and the result here:

```kotlin

// Instant Serializer
object InstantSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): Instant {
        return Instant.parse(decoder.decodeString())
    }

    override fun serialize(encoder: Encoder, value: Instant) {
        encoder.encodeString(value.toString())
    }
}

// Class to be serialized and shown in the schemas
@Serializable
data class RegisterMetadataResponse(
    @Serializable(with = InstantSerializer::class)
    val registreringstidspunkt: Instant,
    val registrertAv: String,
)

private inline fun <reified T> createDefaultPrimitiveTypeData(type: String, format: String): PrimitiveTypeData {
    return PrimitiveTypeData(
        id = TypeId.build(T::class.qualifiedName!!),
        simpleName = T::class.simpleName!!,
        qualifiedName = T::class.qualifiedName!!,
        annotations = mutableListOf(
            AnnotationData(
                name = "type_format_annotation",
                values = mutableMapOf(
                    "type" to type,
                    "format" to format,
                ),
                annotation = null,
            ),
        ),
    )
}

schemas {
    generator = { type ->
        type
            .processKotlinxSerialization {
                customProcessor("Instant") {
                    createDefaultPrimitiveTypeData<Instant>(
                        type = "string",
                        format = "date-time"
                    )
                }
            }
            .connectSubTypes()
            .generateSwaggerSchema()
            .withTitle(TitleType.SIMPLE)
            .handleCoreAnnotations()
            .customizeTypes { typeData, typeSchema ->
                typeData.annotations.find { it.name == "type_format_annotation" }?.also { annotation ->
                    typeSchema.format = annotation.values["format"]?.toString()
                    typeSchema.type = annotation.values["type"]?.toString()
                }
            }
            .handleSchemaAnnotations()
            .compileReferencingRoot()
    }
  }
```

This however results in the type seemingly being null? See:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/cb8f6d7a-d254-489d-aaba-9a1281eac67e">

Also, for some particular reason, using `.processKotlinxSerialization()` turns a different schema into this:

<img width="377" alt="image" src="https://github.com/user-attachments/assets/c0c4f1d4-fbef-4971-be17-2ed83694fc48">

Using `.processReflection()` shows the correct class name, as shown:
<img width="376" alt="image" src="https://github.com/user-attachments/assets/1de6491c-c9a8-4211-b3af-312da4b33200">

**Comment by SMILEY4** [comment]
Hi, sorry for the late response.

Regarding the property type "null":
with openapi3.1 the "types" field is used instead of "type". So 
```kotlin
typeSchema.types = setOf(annotation.values["type"]?.toString())
``` 
should fix the issue. Im thinking to maybe make it so that "type" also works with the next version :thinking: 

Regarding the random string after the class-name in the schema: That comes from a limitiation of kotlinx that i'm facing when generating the schemas of classes where i dont know if generics are involved. You can find a explanation and solution here: https://github.com/SMILEY4/schema-kenerator/issues/37#issuecomment-2416326579.

**Comment by anderssonw** [comment]
Cheers, @SMILEY4 ! I'll check it out with version 4.1.0 if that comes with some QoL stuff :)
