### ISSUE TITLE
defaultUnauthorizedResponse doesn't use a schema reference.

### ISSUE THREAD

**Issue by LynithDev** [SMILEY4/ktor-openapi-tools#159]
```kt
security {
    defaultUnauthorizedResponse {
        body<Errors.AuthenticationRequired>()
    }
}
```
The code above should (in my opinion) create a schema and each protected route would reference that schema's ID. This however is not the case (as seen below)
![image](https://github.com/user-attachments/assets/a7ae2cff-de8f-4813-b27f-78e57c81c6f5)

I'm pretty sure this code might be to blame?

https://github.com/SMILEY4/ktor-swagger-ui/blob/3ac9e7477dbd881413495af42819a63192e1c3c3/ktor-swagger-ui/src/main/kotlin/io/github/smiley4/ktorswaggerui/builder/openapi/ResponsesBuilder.kt#L22-L26

**Comment by SMILEY4** [comment]
Hi, thanks for reporting this.
True, it should store object schemas in the components section as configured in the schema-generation config. 
I fixed the bug with the next version :+1:
