### ISSUE TITLE
Strange behavior with specific field names

### ISSUE THREAD

**Issue by dorohovGeorge** [SMILEY4/ktor-openapi-tools#160]
I have a data class, it has an isClean field. 
<img width="521" alt="image" src="https://github.com/user-attachments/assets/9e81de6a-9fda-4abf-b2ca-3067763ab655">

I found an error when I decided to create an example for route.
<img width="699" alt="image" src="https://github.com/user-attachments/assets/718e2d70-8ba3-4cc7-9345-41f334f304f1">

My "isClean" field became "clean" and I couldn't find any logical explanation for it.
<img width="502" alt="image" src="https://github.com/user-attachments/assets/864584b9-4e05-4b22-8c27-b45a81ff62cb">

 I am using kotlinx-serialisation and there is no problem there, because in a normal response I get an isClean response. Maybe there are some ideas how this can be fixed, I would not want to change the field name in the whole project

**Comment by SMILEY4** [comment]
Hi,
The issue you are facing is that the example objects are encoded to json using jackson by default (happens internally in the swagger-library) - which for some reason interprets "isClean" as "clean".
You can however configure your own example encoder in the plugin config. I've been doing some quick experiments to get it to work with kotlinx:

```kotlin
install(SwaggerUI) {
    examples {
        exampleEncoder = { type, example ->
            if (type is KTypeDescriptor) {
                val jsonString = Json.encodeToString(serializer(type.type), example)
                val jsonObj = jacksonObjectMapper().readValue(jsonString, object : TypeReference<Any>() {})
                jsonObj
            } else {
                example
            }
        }
    }
}
```

This should then produce the same results as the real responses. This encoder will then also be available in the next version by default, likely looking something like this:

```kotlin
install(SwaggerUI) {
    examples {
        exampleEncoder = kotlinxExampleEncoder
    }
}
```

Please let me know if this works for you and if you encounter any issues.

**Comment by dorohovGeorge** [comment]
Thank you very much! That solved my problem!
