### ISSUE TITLE
Request headers does not add in curl request

### ISSUE THREAD

**Issue by MrMak21** [SMILEY4/ktor-openapi-tools#163]
Hello, i am trying to add an Authorization header on my request and even if it shown on the ui then it doesn't include it in the curl request:

`request {
        headerParameter<String>("Authorization") {
            description = "Bearer auth token"
            required = true
            deprecated = false
            explode = false
        }
        body<Unit>()
    }`

**Comment by SMILEY4** [comment]
Hi,
the plugin, swagger or openapi does not look in the parameters for "Authorization"-headers automatically.
You can have a look at this [example](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/ktor-swagger-ui-examples/src/main/kotlin/io/github/smiley4/ktorswaggerui/examples/Authentication.kt) on how to handle authentication with ktor and the swagger-plugin.
I hope this helps and if you have any questions feel free to ask.
