### ISSUE TITLE
Task `checkDebugDuplicateClasses` fails

### ISSUE THREAD

**Issue by ttsatsanis** [SMILEY4/ktor-openapi-tools#164]
Hello,

I'am using the latest version `ktor-swagger-ui` in Android with Ktor 3.0.0 and I got into an issue regarding `io.swagger` dependency.

### Issue:

When trying to build/run my project, the task `chcekxxxDuplicateClasses` failed with the following exception (I removed the whole exception message for clarity):

```
Duplicate class io.swagger.v3.parser.urlresolver.PermittedUrlsChecker found in modules swagger-parser-safe-url-resolver-1.0.70 (io.swagger:swagger-parser-safe-url-resolver:1.0.70) and swagger-parser-safe-url-resolver-2.1.22 (io.swagger.parser.v3:swagger-parser-safe-url-resolver:2.1.22)
...
```

After some time, I discovered with the help of `dependencyInsight` task that both `io.swagger:swagger-parser-safe-url-resolver:1.0.70` and `io.swagger.parser.v3:swagger-parser-safe-url-resolver:2.1.22` are included into the package, which lead to the conflict.

Also, this results in conflict between `javax.validation-api` and `jakarta.validation-api`.

### Resolution

I found out that if someone excludes the group `io.swagger`, no issue occurs.

```
implementation("io.github.smiley4:ktor-swagger-ui:4.1.0") {
      exclude(group = "io.swagger")
}
```

### Conclusion:

I do not know if it is an Android related issue, but it rather seems it is more generic. Also, It might be the wrong project to refer this issue as it seems to be related to your dependent library, `schema-kenerator`.

**Comment by SMILEY4** [comment]
Hi, thanks a lot for reporting this.
I think this may be due to a version missmatch regarding `io.swagger.parser.v3:swagger-parser`?
I'll double check the versions and create a new release. We'll see if that fixes it.

**Comment by ttsatsanis** [comment]
@SMILEY4 happy to help! Whenever the new release is ready, I can also test it.

**Comment by SMILEY4** [comment]
Thanks @ttsatsanis 
I just created [4.1.1](https://github.com/SMILEY4/ktor-swagger-ui/releases/tag/4.1.1), setting the version of `swagger-parser` to the same latest version for both schema-kenerator and ktor-swagger-ui - I hope this fixes these version conflicts.
