### ISSUE TITLE
Jitpack.io vs Maven Central

### ISSUE THREAD

**Issue by poperor** [SMILEY4/ktor-openapi-tools#166]
There are some security concerns regarding jitpack.io. In our company it is even banned for these reasons. Would you consider to use Maven Central in instead of or in addition to jitpack?

**Comment by RowlenZen** [comment]
It seems the usage jitpack already deprecated cause actual version > 3
<img width="943" alt="image" src="https://github.com/user-attachments/assets/716992d2-40f4-49d5-931b-c48fdb5599d7">

**Comment by poperor** [comment]
Yes, you are of course right! I missed that. Thank you!
