### ISSUE TITLE
How to set route as deprecated?

### ISSUE THREAD

**Issue by dmitry-oshurkov** [SMILEY4/ktor-openapi-tools#26]

**Comment by lns-ross** [comment]
Technically it's the operations that are deprecated ... but, yes, this would be a nice enhancement for the DSL at either the operation or the route level (i.e. applies to all operations within route).

**Comment by SMILEY4** [comment]
Hi,   this is currently not possible, but will be added to the next version soon and would then work like this:

Deprecate route "/old"
```kotlin
get("old", {
    deprecated = true
}) {
    call.respondText("...")
}
```

Deprecate everything under "/something" (i.e. "/something/old1" and "/something/old2")
```kotlin
route("something", {
    deprecated = true
}) {
    get("old1", {}) {
        call.respondText("...")
    }
    get("old2", {}) {
        call.respondText("...")
    }
}
```

**Comment by dmitry-oshurkov** [comment]
Thanks!
