### ISSUE TITLE
Unchangeable config value ...?

### ISSUE THREAD

**Issue by lns-ross** [SMILEY4/ktor-openapi-tools#29]
Was this supposed to be a `var`?

https://github.com/SMILEY4/ktor-swagger-ui/blob/290232594177b4716605c22dcf14d19757423f2a/src/main/kotlin/io/github/smiley4/ktorswaggerui/SwaggerUIPluginConfig.kt#L77

**Comment by SMILEY4** [comment]
yes,  this should have been a `var`  :D.   I released a new version [(1.1.1)](https://github.com/SMILEY4/ktor-swagger-ui/releases/tag/1.1.1) that fixes this bug.  Thank you for reporting this.
