### ISSUE TITLE
Allowing examples to be set

### ISSUE THREAD

**Issue by aleksa-djurdjulov** [SMILEY4/ktor-openapi-tools#33]
Is it possible to allow example values to be set for parameters?

I believe there is a related bug here at [this line](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/src/main/kotlin/io/github/smiley4/ktorswaggerui/specbuilder/OApiParametersBuilder.kt#L29). This makes it so that an example is set to `true`/`false`, but the purpose of the parameter is not that and it is explained on [this line](https://github.com/SMILEY4/ktor-swagger-ui/blob/develop/src/main/kotlin/io/github/smiley4/ktorswaggerui/dsl/OpenApiRequestParameter.kt#L49).

**Comment by SMILEY4** [comment]
Hi,   thank you for finding and reporting this.
It seems like these two parameters (example and explode) got mixed up. I quickly created a new version (1.3.1) which fixes this and allows example values to be set for parameters.
