### ISSUE TITLE
Is there any way to ignore path/route?

### ISSUE THREAD

**Issue by chameleon82** [SMILEY4/ktor-openapi-tools#36]
I would like to configure my service endpoint hidden from Swagger UI.

I would prefer to have same behavior as `@ApiOperation(hidden=true)` swagger annotation:
```kotlin
route("health",
  {  hidden = true  } // <- desired property
) {
       get("ready") { call.respond(HttpStatusCode.OK) }
}

```

**Comment by LeatherDeerAU** [comment]
It looks like this functionality already exists if you want to hide the path to some common internal prefix.

[hide route issue](https://github.com/SMILEY4/ktor-swagger-ui/issues/32)

**Comment by SMILEY4** [comment]
hi,  as @LeatherDeerAU already said, you can hide routes via the filter in the config. However, i also want to add the behaviour you proposed in the next version (soon). I will let you know here when this is implemented.
