### ISSUE TITLE
Expose functionality for disabling Swagger validation

### ISSUE THREAD

**Issue by kfh** [SMILEY4/ktor-openapi-tools#4]
It would be nice to have functionality for disabling the default swagger validation that's visible on the landing page. Since in our case we are running all services in a Kubernetes cluster behind a VPN the callback validation always fails and give us an orange box in the right corner that says: INVALID.

**Comment by SMILEY4** [comment]
Hi,
i'm not quite sure which validation or orange box you mean. Do you maybe have a screenshot or know a swagger/openapi-documentation for this ? I'm also having diffuculties reproducing the problem with a minimal example (though i havent done too much experimentation yet).

**Comment by kfh** [comment]
> Hi,
> i'm not quite sure which validation or orange box you mean. Do you maybe have a screenshot or know a swagger/openapi-documentation for this ? I'm also having diffuculties reproducing the problem with a minimal example (though i havent done too much experimentation yet).

Allright, best described by a screenshot probably. 

<img width="1584" alt="invalid" src="https://user-images.githubusercontent.com/186453/197705387-9a7b87c6-c3e7-4175-8427-8a25ff098b6d.png">

So this is activated by default, i'm for sure not doing anything to enable that validation. If the box is clicked one is redirected to _validator.swagger.io_ with an error message indicating the validation failed because it can't reach the server as explained initially.

**Comment by kfh** [comment]
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network

Have a look at the _validatorUrl_ parameter. I would suggest that you expose a thin convenience layer where you offer an boolean property ala _validation_ which defaults to _true_

**Comment by SMILEY4** [comment]
thanks for the hint. The validation doesnt happen when running on localhost, so i didnt catch it when testing.
I created a new version (0.7.0) making this configurable. The validation is now disabled by default, but can be enabled or set to use a custom (self-hosted) validator.

**Comment by kfh** [comment]
> thanks for the hint. The validation doesnt happen when running on localhost, so i didnt catch it when testing.
> I created a new version (0.7.0) making this configurable. The validation is now disabled by default, but can be enabled or set to use a custom (self-hosted) validator.

Thanx! Works great, already deployed the new version 👍
