### ISSUE TITLE
How to document body parameters?

### ISSUE THREAD

**Issue by ScottPierce** [SMILEY4/ktor-openapi-tools#42]
Thank you for providing this library! It's very clean.

How would I describe a Body parameter, and what the acceptable values are for it?

```Kotlin
            body<ExampleRequest> {
                required = true
            }
```

Lets say that ExampleRequest has a parameter `limit` that has a max value of `100`. Or if I wanted to document the acceptable formats for a Date String that was sent. Is that possible currently?

**Comment by SMILEY4** [comment]
Hi,
Thanks. You can customize the schema-objects with the `@Schema`-annotation and add for example add the annotation on the limit-field and set the `maximum`-property. You can find more information here: https://github.com/SMILEY4/ktor-swagger-ui/wiki/Documenting-Routes-(Bodies)#swagger-schema-annotation.

**Comment by ScottPierce** [comment]
@SMILEY4 The models are multiplatform models that are shared between platforms. I can't put annotations on them. Is there another way that I can do this?

**Comment by SMILEY4** [comment]
Unfortunately, there is currently no other way besides annotations.
I'm currently in the process of rewriting the code responsible for handling schemas and objects, so that (describing attributes without annotations/touching the model) might be something i could add in the future.

**Comment by ScottPierce** [comment]
That would be great! This is the only well written library like this for
ktor!

**Comment by chrimaeon** [comment]
@ScottPierce  I've found a workaround for now. You can create your own "schema generation module". have a look at
https://github.com/chrimaeon/curriculumvitae/blob/2f206be18e0ffb25bced113c2ddf24e67cc97a6f/backend/src/main/kotlin/com/cmgapps/ktor/curriculumvitae/infra/victools/CustomModule.kt 
and 
https://github.com/chrimaeon/curriculumvitae/blob/2f206be18e0ffb25bced113c2ddf24e67cc97a6f/backend/src/main/kotlin/com/cmgapps/ktor/curriculumvitae/Application.kt#L177
