### ISSUE TITLE
support webSocket route

### ISSUE THREAD

**Issue by madbulok** [SMILEY4/ktor-openapi-tools#47]
Good day! Tell me if there is an opportunity to add websocket support? 
And how can I turn off generation for **static, file, resources**

Thank you!

**Comment by SMILEY4** [comment]
Hi,
this library focuses on openapi/swagger only, so there is no plan to support websockets.
You can filter out routes with the `pathFilter`-config-option:

```kotlin
install(SwaggerUI) {
    pathFilter = { method, url -> /*return 'false' to exclude them from the api-documentation*/ }
}
```

or directly in the documentation of routes:

```kotlin
get("hidden", {
    hidden = true // exclude this route from the api-documentation
}){
    // ...
}

route("myresources", {
     hidden = true  // exclude all routes below '/myresources' from the api-documentation
}) {
    get {
         //...
    }
}
```
