### ISSUE TITLE
Maven Central Publishing

### ISSUE THREAD

**Issue by SHildebrandt** [SMILEY4/ktor-openapi-tools#49]
Thanks a lot for providing this library! We love it!

Are there any plans to publish this library also to Maven Central? We would like to use it in some projects where we're (unfortunately) restricted to Maven Central.

**Comment by SMILEY4** [comment]
Thank you!
Publishing to maven central is something i am planning to do, though i didn't get to it yet. I'll see what i can do and let you know.

**Comment by SMILEY4** [comment]
I figured out how to publish to maven central, so it should be available now/soon (starting with version 2.2.0).
