### ISSUE TITLE
SchemaAnnotationExample: /swagger-ui/api.json is an emtpy JSON object

### ISSUE THREAD

**Issue by s76527** [SMILEY4/ktor-openapi-tools#53]
I just figured out that since 2.0.0, when I annotate my fields in data classes with `@field:Schema(nullable = true)`, the api.json will be generated with only an empty JSON object `{}`. Same applies to that example in [SchemaAnnotationExample.kt](https://github.com/SMILEY4/ktor-swagger-ui/blob/e35b096ae685022b3e849b5df768d9b2e7651132/src/test/kotlin/io/github/smiley4/ktorswaggerui/examples/SchemaAnnotationExample.kt).

_Edit: correct link reference_

**Comment by SMILEY4** [comment]
Hi,
thank you for reporting this bug.  Its now fixed with version 2.2.2.
