### ISSUE TITLE
The use is complex and not intuitive enough,Suggestions

### ISSUE THREAD

**Issue by s949492225** [SMILEY4/ktor-openapi-tools#54]
Can annotations be used to express interfaces and interface parameters? The current form feels too intrusive, and it is highly complex to use, and the second phase looks unclear. It is suggested to refer to the form of Java,js,python, and these swagger are written in the form of similar annotations.

**Comment by SMILEY4** [comment]
hi,   
thanks for your feedback. However, avoiding annotations is an intentional design choice for this plugin aswell as for ktor and will most likely not be changed.
If you have any more questions, feel free to ask :)
