### ISSUE TITLE
File Upload feature is not working

### ISSUE THREAD

**Issue by x2d7751347m** [SMILEY4/ktor-openapi-tools#58]
https://github.com/SMILEY4/ktor-swagger-ui/wiki/Request-and-Response-Bodies-Basics

I followed the example in the linked wiki above, However, it is displayed as shown in the picture below. 

![2](https://github.com/SMILEY4/ktor-swagger-ui/assets/62936128/48075194-194d-494e-bbd4-374c1bef307c)

The function I want is like the picture below. How do I fix it?

![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/62936128/2a24b589-50b5-4a37-87e3-b82ebef03768)

Here is the code.
```
import java.io.File
...

post({
                request {
                    multipartBody {
                        required = true
                        description = "profile image"
                        mediaType(ContentType.MultiPart.FormData)
                        part<File>("profileImage") {
                            mediaTypes = setOf(
                                ContentType.Image.PNG,
                                ContentType.Image.JPEG,
                                ContentType.Image.GIF
                            )
                        }
                        part<Metadata>("myMetadata")
                    }
                }
            }) {
...
}
```

build.gradle.kts
```
...
dependencies {
    implementation("io.ktor:ktor-server-swagger-jvm:2.3.2")
    implementation("io.ktor:ktor-server-openapi:2.3.2")
    implementation("io.github.smiley4:ktor-swagger-ui:2.2.0")
...
}

**Comment by SMILEY4** [comment]
Hi,
thanks for reporting this issue. The bug is fixed with version 2.2.3 which should be available for download now/soon.
