### ISSUE TITLE
Parameter rootHostPath not pass to requests

### ISSUE THREAD

**Issue by hram** [SMILEY4/ktor-openapi-tools#64]
My server hostet on some domain and some path
For example http://<some_domain>/<some_path>
I setup **rootHostPath** parameter as "/<some_path>"

Swager UI oppends up correctly on URL http://<some_domain>/<some_path>/swagger/index.html
But when I try to send some request URL do not contains rootHostPath in request 

For example if I have routing get /health
Full correct path is **http://<some_domain>/<some_path>/health**

But if I "try it out" in Swager UI
full path is **http://<some_domain>/health**  without **rootHostPath**  parameter

**Comment by SMILEY4** [comment]
Hi,
i currently don't have a setup to properly test this myself, but i think you should be able to control the request-url with the server-configuration like this:
```kotlin
install(SwaggerUI) {
	server {
		url = "https://example.com/my-api"  // or just /my-api
	}
	swagger {
		swaggerUrl = "/swagger-ui"
		rootHostPath = "/my-api"
	}
}
// example curl would then be "curl -X 'GET' 'https://example.com/my-api/hello' -H 'accept: */*'"
```
