### ISSUE TITLE
Wrong pathParameter from resources route

### ISSUE THREAD

**Issue by Giuliopime** [SMILEY4/ktor-openapi-tools#70]
If you have a route that uses ktor `Resources` for type safe routes, the properties of the data class describing the resource are added to the route string generated for swagger.

For example:
```
@Resource(path = "/welcome-action")
class WelcomeActionRoute(val email: String)
```
Will generate
<img width="680" alt="image" src="https://github.com/SMILEY4/ktor-swagger-ui/assets/60524738/2eefa843-1fea-4a9e-9c69-239482c92357">

Even though that is a query parameter, not a path parameter, and I properly described it in the OpenApiDocs of that route
```
get<WelcomeActionRoute>({
        // ...
        request {
            queryParameter<String>("email") {
                description = "the encoded email of the user"
                example = "sample%40mail.com"
                required = true
                allowEmptyValue = false
                allowReserved = false
            }
        }
        // ...
```

Which part of the lib is responsible from doing this?
The resources data classes should be converted to string using only the `path` from the `@Resource` annotation, and ignore every other property of the data class.
I can open a PR if pointed in the right direction to resolve this 👍🏼

**Comment by SMILEY4** [comment]
Thanks a lot!
The responsible code should be in builder/route/RouteCollector.kt#getPath (probably line 66.)

**Comment by Giuliopime** [comment]
Do you plan to release the bug fix? @SMILEY4

**Comment by SMILEY4** [comment]
Yes, ill create it probably tomorrow or until end of this week 👍
