### ISSUE TITLE
[outdated] Documentation Example Serialization

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [SMILEY4/ktor-openapi-tools#76]
`EncodingConfig.encodeExample(value)` does not exist. Which can be used?

`io.github.smiley4:ktor-swagger-ui:2.7.1`

**Comment by Sterta** [comment]
@douglasqueirozalmeida you need to use `EncodingData`  instead of `EncodingConfig`

**Comment by SMILEY4** [comment]
Yes,  to encode a value using the default encoder, `EncodingData.encodeExample(value)` can be used. I'll update the documentation.
