### ISSUE TITLE
Structural error at components.securitySchemes

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [SMILEY4/ktor-openapi-tools#77]
Using https://editor.swagger.io/ to check the generated json presents these problems.

`securityScheme("BasicAuth") {
                type = AuthType.HTTP
                scheme = AuthScheme.BASIC
}`
Structural error at components.securitySchemes.BasicAuth
should NOT have additional 
additionalProperty: name

--------------

`
securityScheme(JWT_AUTH) {
                type = AuthType.HTTP
                scheme = AuthScheme.BEARER
}
`
Structural error at components.securitySchemes.JwtAuth
should NOT have additional properties
additionalProperty: name

**Comment by SMILEY4** [comment]
Thank you!  The bug has been fixed with version 2.7.2
