### ISSUE TITLE
Structural error at components.securitySchemes

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [SMILEY4/ktor-openapi-tools#78]
I don't know if the [documentation](https://github.com/SMILEY4/ktor-swagger-ui/wiki/Authentication) is out of date or if it really is a problem.

```
securityScheme(JWT_SECURITY) {
                type = AuthType.HTTP
                scheme = AuthScheme.BEARER
                bearerFormat = "jwt"
}
```
---
`JSON`
```
"jwtSecurity" : {
        "type" : "http",
        "scheme" : "Bearer",
        "bearerFormat" : "jwt"
      }
```
-----
`Swagger Validate`
```
Structural error at components.securitySchemes.MyJwtAuth
should NOT have a `bearerFormat` property without `scheme: bearer` being set
```

The problem is because the word `Bearer` has the first letter capitalized. It needs to be all in lowercase letters. `bearer`

**Comment by douglasqueirozalmeida** [comment]
@SMILEY4 can you help?

**Comment by SMILEY4** [comment]
Hi,
i can change it to lowercase `bearer`. Though i am not quite sure why the validator reports this as an error. According to https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml `Bearer` should be a valid name.

**Comment by FoorFoxGeek** [comment]
I would like this to be changed back to "Bearer", since I can't use authentication in Swagger UI because of lowercase 'b'.

Taken from https://www.rfc-editor.org/rfc/rfc6750.html#section-2.1

> 
> [2.1](https://www.rfc-editor.org/rfc/rfc6750.html#section-2.1).  Authorization Request Header Field
> 
>    When sending the access token in the "Authorization" request header
>    field defined by HTTP/1.1 [[RFC2617](https://www.rfc-editor.org/rfc/rfc2617)], the client uses the "Bearer"
>    authentication scheme to transmit the access token.
>
