### ISSUE TITLE
How to avoid RateLimit path

### ISSUE THREAD

**Issue by paigham-tech** [SMILEY4/ktor-openapi-tools#80]
Hi, I was integrating swagger ui into my server app.

The server has both global `ratelimits` and route level `ratelimits`.
In case of global rate limit the route generated is working fine, but in case of route level ratelimit, an extra path segement is added like show below, is there a way to avoid this ?
<img width="971" alt="image" src="https://github.com/SMILEY4/ktor-swagger-ui/assets/81463524/50876622-1a65-4717-b8d6-2db9fef53b3f">

**Comment by SMILEY4** [comment]
Hi,
you can ignore parts of the route via the plugin-config. This should then look something like this:
```kotlin
install(SwaggerUI) {
    ignoredRouteSelectors = ignoredRouteSelectors + RateLimitRouteSelector::class
}
```

**Comment by paigham-tech** [comment]
Thanks, this works.
