### ISSUE TITLE
What is the minimum version of the Ktor framework supported by the plugin?

### ISSUE THREAD

**Issue by mishrasangeeta87** [SMILEY4/ktor-openapi-tools#82]
I wanted to understand the compatibility between this plugin and the Ktor framework. To clarify, could you please provide information on the minimum version of Ktor that the plugin requires to operate effectively? Thank you.

**Comment by mishrasangeeta87** [comment]
@SMILEY4  Will you be able to answer this?

**Comment by SMILEY4** [comment]
Hi, i haven't done any extensive compatibility testing, so i cannot tell you exactly. It should be compatible with all ktor 2.x versions.
