### ISSUE TITLE
Doesn't work correctly with RateLimit Plugin

### ISSUE THREAD

**Issue by EchoEllet** [SMILEY4/ktor-openapi-tools#86]
When using Ktor Server RateLimit from the Ktor team, it won't work as it will make the URL invalid

Example code:

Installing the RateLimit plugin and configuring it

```kotlin

install(RateLimit) {
        global {
            rateLimiter(limit = 50, refillPeriod = 1.minutes)
        }
        register(RateLimitName("auth")) {
            rateLimiter(limit = 20, refillPeriod = 5.minutes)
        }
    }

```

Register the **rateLimit** for any route
```kotlin

rateLimit(RateLimitName("auth")) {
            route("/auth") {
                signUpWithEmailAndPassword()
                signInWithEmailAndPassword()
                verifyEmail()
                deleteSelfAccount()
            }
        }

```

![image](https://github.com/SMILEY4/ktor-swagger-ui/assets/73608287/a711f3a6-f248-4be5-9f14-1ef40bbea40f)

When I send a request it send 404 because the URL is not correct because of the `RateLimit auth` in the URL path

**Comment by SMILEY4** [comment]
Hi,
you can ignore the rate-limit part in the url by adding it to the ignored selectors in the plugin config

```kotlin
install(SwaggerUI) {
	ignoredRouteSelectors += RateLimitRouteSelector::class
}
```

I'll also probly add ignore it by default in some future version.

**Comment by EchoEllet** [comment]
> Hi,
> you can ignore the rate-limit part in the url by adding it to the ignored selectors in the plugin config
> 
> ```kotlin
> install(SwaggerUI) {
> 	ignoredRouteSelectors += RateLimitRouteSelector::class
> }
> ```
> 
> I'll also probly add ignore it by default in some future version.

Thanks. Also, it would be nice (even though it's difficult and unlikely to happen) to generate the route info like description from the route comments just like in javascript
