### ISSUE TITLE
Is there a way to hide custom plugin in the swagger UI? and the lock icon doesn't appear on the swagger ui

### ISSUE THREAD

**Issue by phai-non** [SMILEY4/ktor-openapi-tools#88]
I made my own Jwt RouteSelector and using it to protect some routes.

This is my my custom plugin
```kotlin
class AuthRouter(private val tokenType: TokenType) : RouteSelector() {
  override fun evaluate(context: RoutingResolveContext, segmentIndex: Int): RouteSelectorEvaluation =
    RouteSelectorEvaluation.Transparent

  override fun toString(): String {
    return "(${tokenType.name})"
  }
}
```

The problem is, when i open the swagger UI and try to test the api, the `toString()` shows in the route like this
![screen-shot 2024 03 19_04 48 PM](https://github.com/SMILEY4/ktor-swagger-ui/assets/60603701/334b6a02-6896-4ab7-8195-2f66f33ea7bf)
and also show in the url when i send a request like this
![screen-shot 2024 03 19_04 49 PM](https://github.com/SMILEY4/ktor-swagger-ui/assets/60603701/2a4bd44c-077c-485f-a522-930a362e140e)

Is there a option to hide that?

And also i declare a secureSchema
```kotlin
securityScheme("Jwt") {
      type = AuthType.HTTP
      location = AuthKeyLocation.HEADER
      bearerFormat = "jwt"
      scheme = AuthScheme.BEARER
    }
```

and apply it to a route
```kotlin
get<AuthResource.Info>(info) {
      val id = call.getUserId()
      val response = authService.getResidentInfo(id)

      call.respond(response)
    }
...
private val info: OpenApiRoute.() -> Unit = {
  tags = listOf("Auth")
  securitySchemeName = "Jwt"
  request {
    headerParameter<String>("Authorization") {
      description = "Bearer Token"
      required = true
    }
  }
  response {
    HttpStatusCode.OK to {
      body<ResidentInfoDto>()
      description = "success"
    }

    HttpStatusCode.NotFound to {
      body<ErrorResponse>()
      description = "User not Exist!"
    }

    HttpStatusCode.Unauthorized to {
      body<ErrorResponse>()
      description = "Fail to Authenticate"
    }
  }
}
```

but the lock icon doesn't appear on the swagger UI
![screen-shot 2024 03 19_04 54 PM](https://github.com/SMILEY4/ktor-swagger-ui/assets/60603701/c51fb616-c432-4dff-adc9-2606851014f9)
Is there something i missed?

**Comment by SMILEY4** [comment]
Hi,

you should be able to ignore the custom plugin in the url by adding it to the ignored selectors in the plugin config

```kotlin
install(SwaggerUI) {
	ignoredRouteSelectors += AuthRouter::class
}
```

To get the lock-button, you have to mark the route as protected - either by wrapping it in an "authenticated-block" or - more fitting for your case - setting the "protected"-flag.

```kotlin
private val info: OpenApiRoute.() -> Unit = {
    //...
    securitySchemeName = "Jwt"
    protected = true
    //...
}
```

**Comment by phai-non** [comment]
Thank you so much!
