### ISSUE TITLE
Incorrect Endpoint name provided to openTelemetry

### ISSUE THREAD

**Issue by chameleon82** [SMILEY4/ktor-openapi-tools#9]
Hi @SMILEY4 , thanks for that great extension.

Have next issue with exporting tracing data to Jaeger and see next endpoint there:

```
demo-project: /io.github.smiley4.ktorswaggerui.dsl.DocumentedRouteSelector@454d7e70/hello
```

While expect to see 

```
demo-project: /hello
```

I use minimal demo configuration with OpenTelemetry and instrument with https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/ktor/ktor-2.0/library

Issue affect all endpoints defined with `io.github.smiley4.ktorswaggerui.dsl.*`

**Comment by SMILEY4** [comment]
Hi, thanks for reporting the  issue.

i released a new version (1.0.1) that excludes the documented-route from the route-string and should fix this problem.

**Comment by chameleon82** [comment]
Thanks @SMILEY4,
Unfortunately haven't had a chance to test it with new version yet because of https://github.com/jitpack/jitpack.io/issues/5337

**Comment by chameleon82** [comment]
Can confirm, now routes exported correctly:

<img width="1481" alt="Screen Shot 2565-12-27 at 12 39 04" src="https://user-images.githubusercontent.com/2922117/209616818-7abdaecf-2764-43ae-8267-635da32b4319.png">

Thanks for that fast bugfix!
