### ISSUE TITLE
Allow change the path of api.json

### ISSUE THREAD

**Issue by EzequielAlejandroLastra** [SMILEY4/ktor-openapi-tools#95]
Currently the path of open api json is `swaggerUrl ` + `api.json`.

It would be nice if there is an attribute to to set a custom path.

for example: 
swaggerUrl = "/swagger-ui"
documentationPath = "/api/docs"

**Comment by SMILEY4** [comment]
Hi,
i added the option to manually setup the routing for swagger-ui and the api.json in version 2.9.0. See https://github.com/SMILEY4/ktor-swagger-ui/wiki/Manual-Route-Setup for more info.

Let me know if this solves your issue.

**Comment by EzequielAlejandroLastra** [comment]
Hi, Perfect, it is very useful!!!
