### ISSUE TITLE
How to set a queryParameter as type List<String>

### ISSUE THREAD

**Issue by tobyworks** [SMILEY4/ktor-openapi-tools#98]
I have a call that expect a list of strings as a query parameter, as following:

```
endpoint?v=abc&v=xyz
```

but i can't define it as:

```
request{
  queryParameter("v", List<String>::class)
}
```

i can only define it as:

```
request{
  queryParameter("v",List::class)
}
```

but then the swagger docs expects a `array [object]` however im looking for a `array[String]`

**Comment by SMILEY4** [comment]
Hi,

you can specify types as generic type parameters. So writing it like this

```kotlin
queryParameter<List<String>>("v")
```

should solve your problem
